#!/usr/bin/env python3
"""Run the approved deterministic toy zoned-routing benchmark."""

from __future__ import annotations

import csv
import json
from pathlib import Path
import statistics
import sys
import time
from typing import Any


WORKSPACE = Path(__file__).resolve().parents[1]
CASE_PATH = WORKSPACE.parent
SRC = WORKSPACE / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from proxy_router import (  # noqa: E402
    ArchitectureParameters,
    MANY_BODY_FAMILIES,
    PROXY_FAMILIES,
    RoutedMetrics,
    benchmark_gate_streams,
    route_gate_stream,
    synthetic_3sat_terms,
)


DATA_DIR = WORKSPACE / "outputs" / "data"
CHECK_DIR = WORKSPACE / "outputs" / "checks"
FIGURE_DIR = WORKSPACE / "outputs" / "figures"
CONTRACT_PATH = WORKSPACE / "config" / "routing_benchmark_contract.json"


def main() -> int:
    started = time.perf_counter()
    contract = json.loads(CONTRACT_PATH.read_text(encoding="utf-8"))
    _validate_approval(contract)
    architecture = ArchitectureParameters.from_contract(contract)
    run = contract["generated_run"]
    qubit_counts = [int(value) for value in run["qubit_counts"]]
    seeds = [int(value) for value in run["seeds"]]
    clauses_per_qubit = int(run["synthetic_3sat_clauses_per_qubit"])

    families = [str(value) for value in run["families"]]
    if tuple(families) != PROXY_FAMILIES:
        raise ValueError(f"contract families must match the declared eight-family proxy set: {PROXY_FAMILIES}")
    rows: list[dict[str, Any]] = []
    for qubits in qubit_counts:
        for seed in seeds:
            for family in families:
                rows.extend(_run_family(family, qubits, seed, clauses_per_qubit, architecture))

    summary_rows = _aggregate(rows)
    checks = _acceptance_checks(rows, summary_rows, qubit_counts)
    status = "passed" if all(checks.values()) else "failed"
    payload = {
        "schema_version": 1,
        "status": status,
        "paper_id": CASE_PATH.name,
        "target_id": "ROUTING_PROXY",
        "scope": "proxy_model",
        "parameter_match": "proxy_model",
        "reference_comparison": "visual_feature_contract",
        "generated_data_provenance": "independent_numerics",
        "approval": contract["approval"],
        "contract_path": str(CONTRACT_PATH.relative_to(CASE_PATH)),
        "run_shape": {
            "families": run["families"],
            "qubit_counts": qubit_counts,
            "seeds": seeds,
            "rows": len(rows),
            "aggregation": run["aggregation"],
        },
        "architecture": architecture.__dict__,
        "summary": _summary_payload(summary_rows),
        "checks": checks,
        "runtime_seconds": time.perf_counter() - started,
        "decision": {
            "status": "paper_metric_verdict_pass" if status == "passed" else "paper_metric_verdict_stop",
            "next_action": "request_author_artifacts_for_exact_fig4_to_fig8",
            "reason": (
                "The approved eight-family proxy reproduces the paper's qualitative mechanism: all six many-body "
                "families favor retained native supports, while pairwise QFT/GHZ controls remain exactly identical. "
                "It is not a numerical reproduction of Figs. 4-8."
            ),
        },
        "claim_boundary": (
            "All routed curves are generated by the disclosed toy geometry. They validate mechanism and software "
            "plumbing only; author generators, layouts, seeds, route traces, and aggregation remain required for an "
            "exact Fig. 4-8 comparison."
        ),
    }

    DATA_DIR.mkdir(parents=True, exist_ok=True)
    CHECK_DIR.mkdir(parents=True, exist_ok=True)
    FIGURE_DIR.mkdir(parents=True, exist_ok=True)
    _write_rows(DATA_DIR / "proxy_routing_runs.csv", rows)
    _write_rows(DATA_DIR / "proxy_routing_summary.csv", summary_rows)
    _plot_summary(summary_rows, FIGURE_DIR / "proxy_routing_mechanism.png")
    _plot_family_grid(
        summary_rows,
        metric="mean_log_no_fault",
        ylabel="log F",
        title="Fig. 4 proxy — routed log no-fault across eight disclosed families",
        path=FIGURE_DIR / "proxy_fidelity_all_families.png",
    )
    _plot_family_grid(
        summary_rows,
        metric="mean_movement_events",
        ylabel="move events",
        title="Fig. 5 proxy — routed atom movement across eight disclosed families",
        path=FIGURE_DIR / "proxy_moves_all_families.png",
    )
    _plot_family_grid(
        summary_rows,
        metric="mean_scheduled_stages",
        ylabel="scheduled stages",
        title="Fig. 8 proxy — routed stages across eight disclosed families",
        path=FIGURE_DIR / "proxy_stages_all_families.png",
    )
    output_path = CHECK_DIR / "proxy_routing_result.json"
    output_path.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(json.dumps(payload, indent=2, ensure_ascii=False))
    return 0 if status == "passed" else 1


def _validate_approval(contract: dict[str, Any]) -> None:
    approval = contract.get("approval") if isinstance(contract.get("approval"), dict) else {}
    if contract.get("status") != "proxy_approved":
        raise ValueError("routing contract is not approved")
    if approval.get("classification") != "proxy_model" or approval.get("source") != "explicit_conversation_approval":
        raise ValueError("proxy run requires explicit recorded approval")


def _run_family(
    family: str,
    qubits: int,
    seed: int,
    clauses_per_qubit: int,
    architecture: ArchitectureParameters,
) -> list[dict[str, Any]]:
    streams = benchmark_gate_streams(family, qubits, seed, clauses_per_qubit)
    return [
        _row(family, strategy, seed, route_gate_stream(stream, qubits=qubits, architecture=architecture))
        for strategy, stream in streams.items()
    ]


def _row(family: str, strategy: str, seed: int, metrics: RoutedMetrics) -> dict[str, Any]:
    return {"family": family, "strategy": strategy, "seed": seed, **metrics.to_dict()}


def _aggregate(rows: list[dict[str, Any]]) -> list[dict[str, Any]]:
    metric_names = [
        "gate_count",
        "scheduled_stages",
        "movement_events",
        "movement_distance_um",
        "movement_duration_us",
        "transfer_events",
        "idle_exposure",
        "total_duration_us",
        "idle_coherence_us",
        "log_no_fault",
        "no_fault",
        "native_three_qubit_gates",
    ]
    groups: dict[tuple[str, str, int], list[dict[str, Any]]] = {}
    for row in rows:
        key = (str(row["family"]), str(row["strategy"]), int(row["qubits"]))
        groups.setdefault(key, []).append(row)
    result: list[dict[str, Any]] = []
    for (family, strategy, qubits), group in sorted(groups.items()):
        summary: dict[str, Any] = {
            "family": family,
            "strategy": strategy,
            "qubits": qubits,
            "samples": len(group),
        }
        for name in metric_names:
            summary[f"mean_{name}"] = statistics.fmean(float(row[name]) for row in group)
        result.append(summary)
    return result


def _acceptance_checks(
    rows: list[dict[str, Any]],
    summary_rows: list[dict[str, Any]],
    qubit_counts: list[int],
) -> dict[str, bool]:
    lookup = {(row["family"], row["strategy"], row["qubits"]): row for row in summary_rows}
    controls_equal = True
    for family in ("qft_pairs", "ghz_chain"):
        for qubits in qubit_counts:
            native = lookup[(family, "mobius_native", qubits)]
            zap = lookup[(family, "zap_decomposed", qubits)]
            controls_equal &= all(
                native[f"mean_{metric}"] == zap[f"mean_{metric}"]
                for metric in ("gate_count", "scheduled_stages", "movement_events", "total_duration_us", "log_no_fault")
            )

    native_advantage = True
    moves_not_increased = True
    stages_not_increased = True
    for qubits in qubit_counts:
        native = lookup[("synthetic_3sat", "mobius_native", qubits)]
        zap = lookup[("synthetic_3sat", "zap_decomposed", qubits)]
        native_advantage &= native["mean_log_no_fault"] > zap["mean_log_no_fault"]
        moves_not_increased &= native["mean_movement_events"] <= zap["mean_movement_events"]
        stages_not_increased &= native["mean_scheduled_stages"] <= zap["mean_scheduled_stages"]

    all_many_body_improve = all(
        lookup[(family, "mobius_native", qubits)]["mean_log_no_fault"]
        > lookup[(family, "zap_decomposed", qubits)]["mean_log_no_fault"]
        for family in MANY_BODY_FAMILIES
        for qubits in qubit_counts
    )

    deterministic = synthetic_3sat_terms(10, 19, 2) == synthetic_3sat_terms(10, 19, 2)
    bounded_fidelity = all(float(row["log_no_fault"]) <= 1e-12 and 0.0 <= float(row["no_fault"]) <= 1.0 for row in rows)
    return {
        "explicit_proxy_approval_recorded": True,
        "deterministic_replay": deterministic,
        "qft_and_ghz_paths_match_exactly": controls_equal,
        "synthetic_3sat_native_mean_log_fidelity_improves_at_every_size": native_advantage,
        "synthetic_3sat_native_mean_moves_do_not_increase": moves_not_increased,
        "synthetic_3sat_native_mean_stages_do_not_increase": stages_not_increased,
        "all_six_many_body_families_improve_proxy_log_fidelity": all_many_body_improve,
        "all_no_fault_values_bounded": bounded_fidelity,
    }


def _summary_payload(summary_rows: list[dict[str, Any]]) -> dict[str, Any]:
    lookup = {(row["family"], row["strategy"], row["qubits"]): row for row in summary_rows}
    largest = max(int(row["qubits"]) for row in summary_rows)
    family_summary: dict[str, Any] = {}
    for family in PROXY_FAMILIES:
        native = lookup[(family, "mobius_native", largest)]
        zap = lookup[(family, "zap_decomposed", largest)]
        family_summary[family] = {
            "qubits": largest,
            "native_log_no_fault": native["mean_log_no_fault"],
            "zap_log_no_fault": zap["mean_log_no_fault"],
            "log_fidelity_advantage": native["mean_log_no_fault"] - zap["mean_log_no_fault"],
            "native_movement_events": native["mean_movement_events"],
            "zap_movement_events": zap["mean_movement_events"],
            "native_scheduled_stages": native["mean_scheduled_stages"],
            "zap_scheduled_stages": zap["mean_scheduled_stages"],
        }
    return {"largest_size": largest, "families": family_summary}


def _write_rows(path: Path, rows: list[dict[str, Any]]) -> None:
    if not rows:
        raise ValueError("cannot write empty routing data")
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(rows[0]), lineterminator="\n")
        writer.writeheader()
        writer.writerows(rows)


def _plot_summary(rows: list[dict[str, Any]], path: Path) -> None:
    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    lookup = {(row["family"], row["strategy"], row["qubits"]): row for row in rows}
    sizes = sorted({int(row["qubits"]) for row in rows})
    colors = {"mobius_native": "#1f77b4", "zap_decomposed": "#d95f02"}
    labels = {"mobius_native": "Möbius native", "zap_decomposed": "ZAP decomposed"}
    fig, axes = plt.subplots(2, 2, figsize=(10.5, 7.2), constrained_layout=True)
    metrics = [
        ("mean_log_no_fault", "A  3-SAT log no-fault", "log F"),
        ("mean_movement_events", "B  3-SAT movement", "move events"),
        ("mean_scheduled_stages", "C  3-SAT routed stages", "stages"),
    ]
    for axis, (metric, title, ylabel) in zip(axes.flat[:3], metrics):
        for strategy in colors:
            values = [lookup[("synthetic_3sat", strategy, size)][metric] for size in sizes]
            axis.plot(sizes, values, marker="o", color=colors[strategy], label=labels[strategy])
        axis.set_title(title, loc="left", fontweight="bold")
        axis.set_xlabel("qubits")
        axis.set_ylabel(ylabel)
        axis.grid(alpha=0.25)
    axes.flat[0].legend(frameon=False)

    axis = axes.flat[3]
    families = ["synthetic_3sat", "qft_pairs", "ghz_chain"]
    advantages = [
        lookup[(family, "mobius_native", sizes[-1])]["mean_log_no_fault"]
        - lookup[(family, "zap_decomposed", sizes[-1])]["mean_log_no_fault"]
        for family in families
    ]
    axis.bar(["3-SAT", "QFT", "GHZ"], advantages, color=["#1f77b4", "#8c8c8c", "#8c8c8c"])
    axis.axhline(0.0, color="black", linewidth=0.8)
    axis.set_title(f"D  Mechanism control at n={sizes[-1]}", loc="left", fontweight="bold")
    axis.set_ylabel("log-fidelity advantage")
    axis.grid(axis="y", alpha=0.25)
    fig.suptitle("Approved proxy model — not an exact reproduction of Figs. 4–8", fontsize=13)
    fig.savefig(path, dpi=180)
    plt.close(fig)


def _plot_family_grid(
    rows: list[dict[str, Any]],
    *,
    metric: str,
    ylabel: str,
    title: str,
    path: Path,
) -> None:
    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    labels = {
        "synthetic_3sat": "3-SAT oracle",
        "qaoa_3local": "QAOA 3-local",
        "p_spin_ising": "p-spin Ising",
        "hypergraph_4local": "4-local hypergraph",
        "qram_oracle": "QRAM oracle",
        "multiplier_oracle": "Multiplier oracle",
        "qft_pairs": "QFT phase layer",
        "ghz_chain": "GHZ chain",
    }
    colors = {"mobius_native": "#1f77b4", "zap_decomposed": "#d95f02"}
    strategy_labels = {"mobius_native": "Möbius native", "zap_decomposed": "ZAP decomposed"}
    lookup = {(row["family"], row["strategy"], row["qubits"]): row for row in rows}
    sizes = sorted({int(row["qubits"]) for row in rows})
    fig, axes = plt.subplots(2, 4, figsize=(15, 7.2), sharex=True, constrained_layout=True)
    for axis, family in zip(axes.flat, PROXY_FAMILIES):
        for strategy in colors:
            values = [lookup[(family, strategy, size)][metric] for size in sizes]
            axis.plot(sizes, values, marker="o", color=colors[strategy], label=strategy_labels[strategy])
        axis.set_title(labels[family], loc="left", fontsize=10, fontweight="bold")
        axis.set_xlabel("qubits")
        axis.set_ylabel(ylabel)
        axis.grid(alpha=0.25)
    axes.flat[0].legend(frameon=False, fontsize=8)
    fig.suptitle(f"{title}\nproxy_model — not author-exact curves", fontsize=13)
    fig.savefig(path, dpi=180)
    plt.close(fig)


if __name__ == "__main__":
    raise SystemExit(main())
