"""Independent limiting-case checks for the XXZ diffusion paper.

The module evaluates only formulas frozen in the case configuration.  It never
reads the paper, source figures, author arrays, author code, or earlier outputs.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

import numpy as np


ITEMS_BY_TARGET = {
    "T004": ("Claim: hard-rod diffusion limit",),
    "T005": ("Claim: free-model diffusion vanishes",),
    "T006": ("Claim: Navier-Stokes entropy production is non-negative",),
}


def general_classical_diffusion_operator(
    velocities: np.ndarray,
    densities: np.ndarray,
    *,
    scattering_amplitude: float,
    quadrature_weight: float,
) -> np.ndarray:
    """Discretize Eq. (9) for constant scattering and classical ``f=1``.

    The total state density is set to one in this analytic limit, so the
    operator is the weighted graph Laplacian generated by
    ``W_ij=rho_i*a^2*|v_i-v_j|``.
    """

    velocity = np.asarray(velocities, dtype=float)
    density = np.asarray(densities, dtype=float)
    if velocity.ndim != 1 or velocity.shape != density.shape or velocity.size < 2:
        raise ValueError("velocities and densities must be equal one-dimensional arrays")
    if np.any(density <= 0.0):
        raise ValueError("densities must be strictly positive")
    if scattering_amplitude < 0.0 or quadrature_weight <= 0.0:
        raise ValueError("scattering_amplitude must be nonnegative and weight positive")
    kernel = (
        density[:, None]
        * float(scattering_amplitude) ** 2
        * np.abs(velocity[:, None] - velocity[None, :])
    )
    incoming = float(quadrature_weight) * np.sum(kernel, axis=0)
    return np.diag(incoming) - float(quadrature_weight) * kernel


def hard_rod_operator_direct(
    velocities: np.ndarray,
    densities: np.ndarray,
    *,
    rod_length: float,
    quadrature_weight: float,
) -> np.ndarray:
    """Evaluate the known hard-rod operator by its direct component formula."""

    velocity = np.asarray(velocities, dtype=float)
    density = np.asarray(densities, dtype=float)
    if velocity.ndim != 1 or velocity.shape != density.shape or velocity.size < 2:
        raise ValueError("velocities and densities must be equal one-dimensional arrays")
    if np.any(density <= 0.0) or rod_length < 0.0 or quadrature_weight <= 0.0:
        raise ValueError("invalid hard-rod parameters")
    result = np.empty((velocity.size, velocity.size), dtype=float)
    for row in range(velocity.size):
        for column in range(velocity.size):
            if row == column:
                result[row, column] = (
                    quadrature_weight
                    * rod_length**2
                    * np.sum(density * np.abs(velocity - velocity[column]))
                )
            else:
                result[row, column] = (
                    -quadrature_weight
                    * density[row]
                    * rod_length**2
                    * abs(velocity[row] - velocity[column])
                )
    return result


def entropy_production_checks(
    diffusion: np.ndarray,
    densities: np.ndarray,
    *,
    random_seed: int,
    samples: int,
) -> dict[str, Any]:
    """Check positivity of ``sigma^T D C sigma / 2`` in two independent ways."""

    density = np.asarray(densities, dtype=float)
    covariance = np.diag(density)
    quadratic_kernel = np.asarray(diffusion, dtype=float) @ covariance
    symmetry_error = float(np.max(np.abs(quadratic_kernel - quadratic_kernel.T)))
    symmetric_kernel = 0.5 * (quadratic_kernel + quadratic_kernel.T)
    eigenvalues = np.linalg.eigvalsh(symmetric_kernel)
    rng = np.random.default_rng(int(random_seed))
    gradients = rng.normal(size=(int(samples), density.size))
    productions = 0.5 * np.einsum(
        "bi,ij,bj->b", gradients, symmetric_kernel, gradients
    )
    pair_weights = -symmetric_kernel.copy()
    np.fill_diagonal(pair_weights, 0.0)
    differences = gradients[:, :, None] - gradients[:, None, :]
    pairwise_productions = 0.25 * np.einsum(
        "ij,bij->b", pair_weights, differences**2
    )
    minimum_eigenvalue = float(np.min(eigenvalues))
    minimum_sample = float(np.min(productions))
    pairwise_identity_error = float(
        np.max(np.abs(productions - pairwise_productions))
    )
    laplacian_row_sum_error = float(
        np.max(np.abs(np.sum(symmetric_kernel, axis=1)))
    )
    minimum_pair_weight = float(np.min(pair_weights))
    passed = (
        samples >= 8
        and symmetry_error < 1.0e-12
        and minimum_eigenvalue >= -1.0e-12
        and minimum_sample >= -1.0e-12
        and minimum_pair_weight >= -1.0e-12
        and pairwise_identity_error < 1.0e-12
        and laplacian_row_sum_error < 1.0e-12
    )
    return {
        "status": "passed" if passed else "failed",
        "symmetry_error": symmetry_error,
        "minimum_eigenvalue": minimum_eigenvalue,
        "minimum_sampled_entropy_production": minimum_sample,
        "minimum_pair_weight": minimum_pair_weight,
        "pairwise_square_identity_error": pairwise_identity_error,
        "laplacian_row_sum_error": laplacian_row_sum_error,
        "samples": int(samples),
        "independent_checks": [
            "symmetric_eigenspectrum",
            "random_quadratic_forms",
            "weighted_pairwise_square_identity",
            "graph_laplacian_row_sum",
        ],
    }


def run_campaign(config: dict[str, Any], output_root: Path) -> dict[str, Any]:
    if config.get("paper_id") != "1807.02414":
        raise ValueError("paper_id must be 1807.02414")
    parameters = config.get("parameters")
    if not isinstance(parameters, dict):
        raise ValueError("parameters must be an object")
    if parameters.get("profile") != "reduced_analytic_attestation":
        raise ValueError("only the frozen reduced analytic profile is accepted")

    hard = parameters["hard_rod"]
    velocities = np.asarray(hard["velocities"], dtype=float)
    densities = np.asarray(hard["densities"], dtype=float)
    amplitude = float(hard["rod_length"])
    weight = float(hard["quadrature_weight"])
    general = general_classical_diffusion_operator(
        velocities,
        densities,
        scattering_amplitude=amplitude,
        quadrature_weight=weight,
    )
    direct = hard_rod_operator_direct(
        velocities,
        densities,
        rod_length=amplitude,
        quadrature_weight=weight,
    )
    hard_error = float(np.max(np.abs(general - direct)))
    conservation_error = float(np.max(np.abs(np.sum(general, axis=0))))
    hard_passed = hard_error < 1.0e-12 and conservation_error < 1.0e-12

    free = general_classical_diffusion_operator(
        velocities,
        densities,
        scattering_amplitude=0.0,
        quadrature_weight=weight,
    )
    free_maximum = float(np.max(np.abs(free)))
    free_passed = free_maximum == 0.0

    entropy = entropy_production_checks(
        general,
        densities,
        random_seed=int(parameters["entropy"]["random_seed"]),
        samples=int(parameters["entropy"]["samples"]),
    )
    target_checks = {
        "T004": {
            "status": "passed" if hard_passed else "failed",
            "maximum_direct_reduction_error": hard_error,
            "column_conservation_error": conservation_error,
            "independent_checks": ["matrix_formula_comparison", "conservation_law"],
        },
        "T005": {
            "status": "passed" if free_passed else "failed",
            "maximum_zero_scattering_operator_entry": free_maximum,
            "independent_checks": ["zero_kernel_limit", "exact_zero_operator"],
        },
        "T006": entropy,
    }
    for check in target_checks.values():
        check["profile"] = parameters["profile"]
        check["paper_scale_executed"] = False

    item_results = {
        item_id: {
            "target_id": target_id,
            "implementation_status": (
                "attested" if target_checks[target_id]["status"] == "passed" else "failed"
            ),
            "scientific_coverage_changed": False,
        }
        for target_id, item_ids in ITEMS_BY_TARGET.items()
        for item_id in item_ids
    }
    status = (
        "passed"
        if all(check["status"] == "passed" for check in target_checks.values())
        else "failed"
    )
    return {
        "schema_version": 1,
        "paper_id": config["paper_id"],
        "status": status,
        "profile": parameters["profile"],
        "fixed_item_denominator": len(item_results),
        "item_results": item_results,
        "target_checks": target_checks,
        "scientific_coverage_changed": False,
        "scientific_boundary": (
            "Analytic limiting paths are implementation-attested; they are not promoted "
            "to accepted paper reproduction without fresh scientific review."
        ),
        "numerical_input_boundary": {
            "paper_pdf_or_tex_read": False,
            "author_code_or_arrays_read": False,
            "reference_pixels_read": False,
            "historical_outputs_read": False,
        },
    }
