"""Hamiltonians and evolution operators derived from the published equations."""

from __future__ import annotations

import numpy as np
from scipy.linalg import expm

SIGMA_X = np.array([[0.0, 1.0], [1.0, 0.0]], dtype=complex)
SIGMA_Y = np.array([[0.0, -1.0j], [1.0j, 0.0]], dtype=complex)
SIGMA_Z = np.array([[1.0, 0.0], [0.0, -1.0]], dtype=complex)
IDENTITY_2 = np.eye(2, dtype=complex)
SQUARE_BONDS = ((1.0, 0.0), (0.0, 1.0), (-1.0, 0.0), (0.0, -1.0))


def expm_hermitian_2x2(matrix: np.ndarray, duration: float) -> np.ndarray:
    """Exponentiate a traceless 2x2 Hermitian matrix analytically."""

    norm = float(np.sqrt(max(0.0, np.trace(matrix @ matrix).real / 2.0)))
    if norm < 1e-15:
        return IDENTITY_2.copy()
    angle = norm * duration
    return np.cos(angle) * IDENTITY_2 - 1.0j * np.sin(angle) * matrix / norm


def square_coordinates(q1: float, q2: float) -> tuple[float, float]:
    """Map primitive reciprocal coordinates to Cartesian momentum.

    The primitive real-space cell is generated by (a,a) and (a,-a).  The
    q-coordinate torus is periodic up to the sublattice gauge SIGMA_Z.
    """

    return 0.5 * (q1 + q2), 0.5 * (q1 - q2)


def square_bloch_step(
    q1: float,
    q2: float,
    hopping: float,
    sublattice: float,
    step: int,
) -> np.ndarray:
    """Return one of the five piecewise-constant Bloch Hamiltonians."""

    if step not in range(5):
        raise ValueError("step must be 0, 1, 2, 3, or 4")
    if step == 4:
        return sublattice * SIGMA_Z
    kx, ky = square_coordinates(q1, q2)
    bx, by = SQUARE_BONDS[step]
    phase = bx * kx + by * ky
    hopping_matrix = np.cos(phase) * SIGMA_X - np.sin(phase) * SIGMA_Y
    return -hopping * hopping_matrix + sublattice * SIGMA_Z


def square_bloch_evolution(
    q1: float,
    q2: float,
    hopping: float,
    sublattice: float,
    time: float,
    *,
    period: float = 1.0,
) -> np.ndarray:
    """Evaluate the exact piecewise evolution at any time in one period."""

    if not 0.0 <= time <= period:
        raise ValueError("time must lie within one driving period")
    segment = period / 5.0
    result = IDENTITY_2.copy()
    for step in range(5):
        elapsed = min(max(time - step * segment, 0.0), segment)
        if elapsed > 0.0:
            result = (
                expm_hermitian_2x2(
                    square_bloch_step(q1, q2, hopping, sublattice, step), elapsed
                )
                @ result
            )
    return result


def square_floquet_bloch(
    q1: float,
    q2: float,
    hopping: float,
    sublattice: float,
    *,
    period: float = 1.0,
) -> np.ndarray:
    return square_bloch_evolution(q1, q2, hopping, sublattice, period, period=period)


def square_strip_step(
    momentum: float,
    width: int,
    hopping: float,
    sublattice: float,
    step: int,
) -> np.ndarray:
    """Partial-Fourier strip Hamiltonian with open transverse boundaries."""

    if width < 2:
        raise ValueError("strip width must be at least two cells")
    if step not in range(5):
        raise ValueError("step must be 0, 1, 2, 3, or 4")
    dimension = 2 * width
    matrix = np.zeros((dimension, dimension), dtype=complex)
    for layer in range(width):
        matrix[2 * layer, 2 * layer] = sublattice
        matrix[2 * layer + 1, 2 * layer + 1] = -sublattice
    if step == 4:
        return matrix

    if step in {0, 2}:
        phase = momentum if step == 0 else -momentum
        for layer in range(width):
            a_index = 2 * layer
            b_index = a_index + 1
            amplitude = -hopping * np.exp(1.0j * phase)
            matrix[a_index, b_index] = amplitude
            matrix[b_index, a_index] = amplitude.conjugate()
    else:
        for layer in range(width - 1):
            if step == 1:
                a_index = 2 * (layer + 1)
                b_index = 2 * layer + 1
            else:
                a_index = 2 * layer
                b_index = 2 * (layer + 1) + 1
            matrix[a_index, b_index] = -hopping
            matrix[b_index, a_index] = -hopping
    return matrix


def square_floquet_strip(
    momentum: float,
    width: int,
    hopping: float,
    sublattice: float,
    *,
    period: float = 1.0,
) -> np.ndarray:
    segment = period / 5.0
    result = np.eye(2 * width, dtype=complex)
    for step in range(5):
        result = (
            expm(
                -1.0j
                * square_strip_step(momentum, width, hopping, sublattice, step)
                * segment
            )
            @ result
        )
    return result


def quasienergy_eigensystem(
    floquet_operator: np.ndarray, *, period: float = 1.0
) -> tuple[np.ndarray, np.ndarray]:
    values, vectors = np.linalg.eig(floquet_operator)
    energies = -np.angle(values) / period
    order = np.argsort(energies)
    vectors = vectors[:, order]
    vectors /= np.linalg.norm(vectors, axis=0, keepdims=True)
    return energies[order], vectors


def strip_edge_observables(
    vectors: np.ndarray, *, layers_per_edge: int = 2
) -> tuple[np.ndarray, np.ndarray]:
    """Return total boundary weight and signed top-minus-bottom weight."""

    dimension = vectors.shape[0]
    if dimension % 2:
        raise ValueError("strip vectors must have two sublattice states per layer")
    width = dimension // 2
    layers = min(layers_per_edge, width // 2)
    probability = np.abs(vectors) ** 2
    bottom = probability[: 2 * layers].sum(axis=0)
    top = probability[-2 * layers :].sum(axis=0)
    return bottom + top, top - bottom


def weak_bloch_vector(
    kx: float,
    ky: float,
    *,
    mu: float,
    hopping: float,
    mass_curvature: float,
    spin_orbit: float,
) -> np.ndarray:
    return np.array(
        [
            spin_orbit * np.sin(kx),
            spin_orbit * np.sin(ky),
            (mu - hopping)
            - 2.0 * mass_curvature * (2.0 - np.cos(kx) - np.cos(ky))
            + hopping * np.cos(kx) * np.cos(ky),
        ],
        dtype=float,
    )


def weak_bloch_hamiltonian(
    kx: float,
    ky: float,
    *,
    mu: float,
    hopping: float,
    mass_curvature: float,
    spin_orbit: float,
) -> np.ndarray:
    dx, dy, dz = weak_bloch_vector(
        kx,
        ky,
        mu=mu,
        hopping=hopping,
        mass_curvature=mass_curvature,
        spin_orbit=spin_orbit,
    )
    return dx * SIGMA_X + dy * SIGMA_Y + dz * SIGMA_Z


def weak_strip_hamiltonian(
    kx: float,
    width: int,
    *,
    mu: float,
    hopping: float,
    mass_curvature: float,
    spin_orbit: float,
) -> np.ndarray:
    """Cylinder Hamiltonian obtained by Fourier transforming only x."""

    onsite = (
        spin_orbit * np.sin(kx) * SIGMA_X
        + ((mu - hopping) - 4.0 * mass_curvature + 2.0 * mass_curvature * np.cos(kx))
        * SIGMA_Z
    )
    interlayer = (
        mass_curvature + 0.5 * hopping * np.cos(kx)
    ) * SIGMA_Z + spin_orbit * SIGMA_Y / (2.0j)
    matrix = np.zeros((2 * width, 2 * width), dtype=complex)
    for layer in range(width):
        slc = slice(2 * layer, 2 * layer + 2)
        matrix[slc, slc] = onsite
        if layer + 1 < width:
            nxt = slice(2 * (layer + 1), 2 * (layer + 2))
            matrix[nxt, slc] = interlayer
            matrix[slc, nxt] = interlayer.conjugate().T
    return matrix


def weak_strip_hamiltonian_from_bloch_quadrature(
    kx: float,
    width: int,
    *,
    mu: float,
    hopping: float,
    mass_curvature: float,
    spin_orbit: float,
    quadrature_points: int = 16,
) -> np.ndarray:
    """Independent partial Fourier transform of the printed Bloch model.

    This deliberately reconstructs the onsite and nearest-layer blocks by
    discrete Fourier quadrature instead of reusing the hand-derived bond
    coefficients in :func:`weak_strip_hamiltonian`.  Because the paper's
    Bloch Hamiltonian contains only first harmonics in ``ky``, any grid with at
    least four points recovers those blocks to roundoff.
    """

    if width < 2:
        raise ValueError("strip width must be at least two cells")
    if quadrature_points < 4:
        raise ValueError("quadrature_points must be at least four")
    ky_grid = 2.0 * np.pi * np.arange(quadrature_points) / quadrature_points
    bloch = np.asarray(
        [
            weak_bloch_hamiltonian(
                kx,
                ky,
                mu=mu,
                hopping=hopping,
                mass_curvature=mass_curvature,
                spin_orbit=spin_orbit,
            )
            for ky in ky_grid
        ]
    )
    onsite = np.mean(bloch, axis=0)
    forward = np.mean(bloch * np.exp(-1.0j * ky_grid)[:, None, None], axis=0)
    matrix = np.zeros((2 * width, 2 * width), dtype=complex)
    for layer in range(width):
        current = slice(2 * layer, 2 * layer + 2)
        matrix[current, current] = onsite
        if layer + 1 < width:
            following = slice(2 * (layer + 1), 2 * (layer + 2))
            matrix[following, current] = forward
            matrix[current, following] = forward.conjugate().T
    return matrix


def weak_floquet_strip_hamiltonian(
    kx: float,
    width: int,
    truncation: int,
    *,
    mu: float,
    hopping: float,
    mass_curvature: float,
    spin_orbit: float,
    drive_amplitude: float,
    drive_frequency: float,
) -> np.ndarray:
    """Eq. (20) truncated to -M <= m <= M for a cosine drive."""

    static = weak_strip_hamiltonian(
        kx,
        width,
        mu=mu,
        hopping=hopping,
        mass_curvature=mass_curvature,
        spin_orbit=spin_orbit,
    )
    block_dimension = static.shape[0]
    copies = 2 * truncation + 1
    result = np.zeros(
        (copies * block_dimension, copies * block_dimension), dtype=complex
    )
    drive = 0.5 * drive_amplitude * np.kron(np.eye(width), SIGMA_Z)
    for block, photon in enumerate(range(-truncation, truncation + 1)):
        slc = slice(block * block_dimension, (block + 1) * block_dimension)
        result[slc, slc] = static + photon * drive_frequency * np.eye(block_dimension)
        if block + 1 < copies:
            nxt = slice((block + 1) * block_dimension, (block + 2) * block_dimension)
            result[slc, nxt] = drive
            result[nxt, slc] = drive
    return result


def weak_floquet_bloch(
    kx: float,
    ky: float,
    *,
    mu: float,
    hopping: float,
    mass_curvature: float,
    spin_orbit: float,
    drive_amplitude: float,
    drive_frequency: float,
    time_steps: int,
) -> np.ndarray:
    """Midpoint product for one harmonic driving period."""

    period = 2.0 * np.pi / drive_frequency
    dt = period / time_steps
    static = weak_bloch_hamiltonian(
        kx,
        ky,
        mu=mu,
        hopping=hopping,
        mass_curvature=mass_curvature,
        spin_orbit=spin_orbit,
    )
    result = IDENTITY_2.copy()
    for index in range(time_steps):
        time = (index + 0.5) * dt
        hamiltonian = (
            static + drive_amplitude * np.cos(drive_frequency * time) * SIGMA_Z
        )
        result = expm_hermitian_2x2(hamiltonian, dt) @ result
    return result
