"""Independent numerics for the Bender-Boettcher PT-symmetric spectrum."""

from .model import (
    airy_matching_derivative,
    build_contour_hamiltonian,
    classical_escape_angle,
    classical_period,
    classical_spiral_trajectory,
    contour_geometry,
    exceptional_point_discriminant,
    ground_state_shooting,
    locate_exceptional_point,
    low_spectrum,
    massive_n1_energy,
    near_one_asymptotic_energy,
    shooting_patch_residual,
    shifted_oscillator_energy,
    stokes_wedge_angles,
    turning_point_angle,
    turning_point_passages,
    turning_points_before_escape,
    wkb_branch_cut_intersection_imag,
    wkb_energy,
)

__all__ = [
    "airy_matching_derivative",
    "build_contour_hamiltonian",
    "classical_escape_angle",
    "classical_period",
    "classical_spiral_trajectory",
    "contour_geometry",
    "exceptional_point_discriminant",
    "ground_state_shooting",
    "locate_exceptional_point",
    "low_spectrum",
    "massive_n1_energy",
    "near_one_asymptotic_energy",
    "shooting_patch_residual",
    "shifted_oscillator_energy",
    "stokes_wedge_angles",
    "turning_point_angle",
    "turning_point_passages",
    "turning_points_before_escape",
    "wkb_branch_cut_intersection_imag",
    "wkb_energy",
]
