#!/usr/bin/env python3
"""Build Supplement Figure S5 from independently simulated periodic-chain I3 data.

The input is the reusable transition ensemble generated by ``run_main_fig2``.
This program never opens a source figure and never digitizes a paper curve.
Published Table SI values are consulted only after every fit has completed.
"""

from __future__ import annotations

import argparse
import csv
from dataclasses import asdict, dataclass
import json
import os
from pathlib import Path
import sys
from time import perf_counter
from typing import Iterable


WORKSPACE = Path(__file__).resolve().parents[1]
os.environ.setdefault("MPLCONFIGDIR", str(WORKSPACE / "outputs" / "cache" / "matplotlib"))

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402
import numpy as np  # noqa: E402

sys.path.insert(0, str(WORKSPACE / "src"))

from finite_size_scaling import (  # noqa: E402
    ScalingCurve,
    bootstrap_measurement_fractions,
    collapse_cost,
    fit_data_collapse,
    leave_one_size_out_fits,
    scaled_curve,
)


TARGET_ID = "T005"
DISPLAY_DEPTHS = (1, 7, 31)
PAPER_DEPTHS = (1, 3, 5, 7, 11, 15, 23, 31)
DISPLAY_CRITICAL_HALF_WIDTH = 0.04
PUBLISHED_ACCEPTANCE = {
    1: (0.162, 1.28),
    3: (0.412, 1.28),
    5: (0.589, 1.27),
    7: (0.707, 1.26),
    11: (0.826, 1.12),
    15: (0.862, 1.30),
    23: (0.883, 1.25),
    31: (0.886, 1.21),
}


@dataclass(frozen=True)
class FitRecord:
    depth: int
    critical_probability: float
    critical_probability_error: float
    critical_exponent: float
    critical_exponent_error: float
    cost: float
    unscaled_cost: float
    probability_at_boundary: bool
    exponent_at_boundary: bool
    leave_one_size_out_probability_span: float


def require_guard() -> None:
    if os.environ.get("PRAGENT_GUARDED_TARGET_ID", "") != TARGET_ID:
        raise RuntimeError(
            "Run this target through PRAgent-workflow/scripts/run_target.py so the live formula gate is enforced."
        )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--input",
        type=Path,
        default=WORKSPACE / "outputs" / "data" / "main_fig2_numerical_data.csv",
    )
    parser.add_argument(
        "--refinement-input",
        type=Path,
        action="append",
        default=[],
        help="Additional independently generated transition rows to merge before fitting.",
    )
    parser.add_argument("--bootstrap-samples", type=int, default=100)
    parser.add_argument("--seed", type=int, default=1_903_051_245)
    return parser.parse_args()


def load_transition_curves(
    paths: Path | Iterable[Path],
) -> dict[int, tuple[ScalingCurve, ...]]:
    input_paths = (paths,) if isinstance(paths, Path) else tuple(paths)
    if not input_paths:
        raise ValueError("at least one independent numerical input is required")
    grouped: dict[tuple[int, int], list[dict[str, str]]] = {}
    seen_coordinates: set[tuple[int, int, float]] = set()
    for path in input_paths:
        with path.open(encoding="utf-8", newline="") as handle:
            for row in csv.DictReader(handle):
                if row["campaign"] != "transition" or row["observable"] != "tripartite_mutual_information":
                    continue
                key = (int(row["d"]), int(row["L"]))
                coordinate = (key[0], key[1], round(float(row["p"]), 14))
                if coordinate in seen_coordinates:
                    raise ValueError(f"duplicate transition coordinate across inputs: {coordinate}")
                seen_coordinates.add(coordinate)
                grouped.setdefault(key, []).append(row)
    if not grouped:
        raise ValueError("input contains no independently generated transition I3 rows")

    depths = sorted({depth for depth, _ in grouped})
    if tuple(depths) != PAPER_DEPTHS:
        raise ValueError(f"expected depths {PAPER_DEPTHS}, got {tuple(depths)}")
    result: dict[int, tuple[ScalingCurve, ...]] = {}
    for depth in depths:
        curves: list[ScalingCurve] = []
        for (row_depth, size), rows in sorted(grouped.items()):
            if row_depth != depth:
                continue
            ordered = sorted(rows, key=lambda row: float(row["p"]))
            probabilities = np.asarray([float(row["p"]) for row in ordered])
            means = np.asarray([float(row["mean"]) for row in ordered])
            errors = np.asarray(
                [
                    max(float(row["standard_error"]), 1.0 / np.sqrt(int(row["realizations"])))
                    for row in ordered
                ]
            )
            curves.append(
                ScalingCurve(
                    size=size,
                    measurement_fraction=probabilities,
                    observable=means,
                    standard_error=errors,
                )
            )
        grids = {tuple(np.round(curve.measurement_fraction, 12)) for curve in curves}
        if len(curves) < 4 or len(grids) != 1:
            raise ValueError(f"depth {depth} requires at least four sizes on one p grid")
        result[depth] = tuple(curves)
    return result


def fit_all_depths(
    curves_by_depth: dict[int, tuple[ScalingCurve, ...]],
    *,
    bootstrap_samples: int,
    seed: int,
) -> tuple[FitRecord, ...]:
    records: list[FitRecord] = []
    for depth_index, depth in enumerate(PAPER_DEPTHS):
        curves = curves_by_depth[depth]
        probabilities = curves[0].measurement_fraction
        fit_kwargs = {
            "critical_probability_bounds": (float(probabilities[0]), float(probabilities[-1])),
            "critical_exponent_bounds": (0.7, 1.8),
            "grid_points": 17,
            "refinement_rounds": 2,
        }
        fit = fit_data_collapse(curves, **fit_kwargs)
        omitted = leave_one_size_out_fits(curves, **fit_kwargs)
        bootstrap = bootstrap_measurement_fractions(
            curves,
            samples=bootstrap_samples,
            sample_fraction=0.8,
            seed=seed + depth_index,
            **fit_kwargs,
        )
        omitted_pc = np.asarray([item.critical_probability for item in omitted.values()])
        probability_error = max(
            float(np.std(omitted_pc, ddof=1)),
            float(np.std(bootstrap.critical_probabilities, ddof=1)),
            float((probabilities[1] - probabilities[0]) / 2),
        )
        exponent_error = max(float(np.std(bootstrap.critical_exponents, ddof=1)), 0.01)
        unscaled_cost, _ = collapse_cost(
            curves,
            critical_probability=fit.critical_probability,
            critical_exponent=100.0,
        )
        records.append(
            FitRecord(
                depth=depth,
                critical_probability=fit.critical_probability,
                critical_probability_error=probability_error,
                critical_exponent=fit.critical_exponent,
                critical_exponent_error=exponent_error,
                cost=fit.cost,
                unscaled_cost=unscaled_cost,
                probability_at_boundary=fit.critical_probability_at_boundary,
                exponent_at_boundary=fit.critical_exponent_at_boundary,
                leave_one_size_out_probability_span=float(np.ptp(omitted_pc)),
            )
        )
    return tuple(records)


def write_data_csv(
    path: Path,
    curves_by_depth: dict[int, tuple[ScalingCurve, ...]],
    fits: tuple[FitRecord, ...],
) -> None:
    fit_by_depth = {fit.depth: fit for fit in fits}
    fields = ["panel", "kind", "depth", "L", "p", "scaled_x", "I3", "standard_error"]
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fields, lineterminator="\n")
        writer.writeheader()
        for column, depth in enumerate(DISPLAY_DEPTHS):
            scan_panel = chr(ord("a") + column)
            collapse_panel = chr(ord("d") + column)
            fit = fit_by_depth[depth]
            for curve in curves_by_depth[depth]:
                scaled_x, observable, error = scaled_curve(
                    curve,
                    critical_probability=fit.critical_probability,
                    critical_exponent=fit.critical_exponent,
                    subtract_at_critical_probability=False,
                )
                for index, probability in enumerate(curve.measurement_fraction):
                    common = {
                        "depth": depth,
                        "L": curve.size,
                        "p": float(probability),
                        "I3": float(observable[index]),
                        "standard_error": float(error[index]),
                    }
                    writer.writerow({"panel": scan_panel, "kind": "scan", "scaled_x": "", **common})
                    writer.writerow(
                        {
                            "panel": collapse_panel,
                            "kind": "collapse",
                            "scaled_x": float(scaled_x[index]),
                            **common,
                        }
                    )


def write_fit_csv(path: Path, fits: tuple[FitRecord, ...]) -> None:
    fields = list(asdict(fits[0]))
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fields, lineterminator="\n")
        writer.writeheader()
        for fit in fits:
            writer.writerow(asdict(fit))


def render(
    path: Path,
    curves_by_depth: dict[int, tuple[ScalingCurve, ...]],
    fits: tuple[FitRecord, ...],
) -> None:
    fit_by_depth = {fit.depth: fit for fit in fits}
    plt.rcParams.update({"font.size": 9.5, "axes.linewidth": 0.8})
    figure = plt.figure(figsize=(16, 6), constrained_layout=True)
    grid = figure.add_gridspec(2, 4, width_ratios=(1, 1, 1, 1.15))
    axes = []
    for column, depth in enumerate(DISPLAY_DEPTHS):
        scan_axis = figure.add_subplot(grid[0, column])
        collapse_axis = figure.add_subplot(grid[1, column])
        axes.extend((scan_axis, collapse_axis))
        curves = curves_by_depth[depth]
        colors = plt.cm.viridis(np.linspace(0.05, 0.9, len(curves)))
        fit = fit_by_depth[depth]
        for curve, color in zip(curves, colors):
            scan_mask = (
                np.abs(curve.measurement_fraction - fit.critical_probability)
                <= DISPLAY_CRITICAL_HALF_WIDTH + 1e-12
            )
            scan_axis.plot(
                curve.measurement_fraction[scan_mask],
                curve.observable[scan_mask],
                color=color,
                marker="o",
                markersize=2.8,
                linewidth=1.0,
            )
            scaled_x, observable, error = scaled_curve(
                curve,
                critical_probability=fit.critical_probability,
                critical_exponent=fit.critical_exponent,
                subtract_at_critical_probability=False,
            )
            collapse_mask = np.abs(scaled_x) <= 1.05
            collapse_axis.plot(
                scaled_x[collapse_mask],
                observable[collapse_mask],
                color=color,
                marker="o",
                markersize=2.6,
                linewidth=1.0,
            )
        scan_axis.set_xlim(
            max(0.0, fit.critical_probability - DISPLAY_CRITICAL_HALF_WIDTH),
            min(1.0, fit.critical_probability + DISPLAY_CRITICAL_HALF_WIDTH),
        )
        scan_axis.set_xlabel(r"$p$")
        scan_axis.set_ylabel(r"$I_3$")
        collapse_axis.set_xlabel(r"$(p-p_c)L^{1/\nu}$")
        collapse_axis.set_ylabel(r"$I_3$")
        collapse_axis.set_xlim(-1.1, 1.1)
        scan_axis.text(-0.20, 1.03, f"({chr(ord('a') + column)})", transform=scan_axis.transAxes, fontsize=13)
        collapse_axis.text(-0.20, 1.03, f"({chr(ord('d') + column)})", transform=collapse_axis.transAxes, fontsize=13)

    exponent_axis = figure.add_subplot(grid[:, 3])
    depths = np.asarray([fit.depth for fit in fits])
    exponents = np.asarray([fit.critical_exponent for fit in fits])
    errors = np.asarray([fit.critical_exponent_error for fit in fits])
    exponent_axis.errorbar(
        depths,
        exponents,
        yerr=errors,
        fmt="D",
        fillstyle="none",
        color="#0879bd",
        ecolor="#0879bd",
        markersize=4.5,
        capsize=2.5,
        linewidth=1.0,
    )
    exponent_axis.set_xlim(0, 33)
    exponent_axis.set_ylim(0, 2)
    exponent_axis.set_xlabel(r"$d$")
    exponent_axis.set_ylabel(r"$\nu$")
    exponent_axis.text(-0.17, 1.03, "(g)", transform=exponent_axis.transAxes, fontsize=13)
    axes.append(exponent_axis)
    for axis in axes:
        axis.tick_params(direction="in", top=True, right=True)
    figure.savefig(path, dpi=180, facecolor="white")
    plt.close(figure)


def build_checks(
    curves_by_depth: dict[int, tuple[ScalingCurve, ...]],
    fits: tuple[FitRecord, ...],
    *,
    generated_data_provenance: str = "independent_numerics_reused_from_T001",
) -> dict[str, object]:
    monotonic_flags: list[bool] = []
    volume_order_flags: list[bool] = []
    for depth in DISPLAY_DEPTHS:
        curves = curves_by_depth[depth]
        for curve in curves:
            differences = np.diff(curve.observable)
            tolerance = max(0.5, float(np.median(curve.standard_error)))
            monotonic_flags.extend(bool(value >= -tolerance) for value in differences)
        low_p_values = [curve.observable[0] for curve in curves]
        volume_order_flags.extend(
            bool(right <= left + 1.0)
            for left, right in zip(low_p_values, low_p_values[1:])
        )

    pc_errors = {
        fit.depth: abs(fit.critical_probability - PUBLISHED_ACCEPTANCE[fit.depth][0])
        for fit in fits
    }
    nu_errors = {
        fit.depth: abs(fit.critical_exponent - PUBLISHED_ACCEPTANCE[fit.depth][1])
        for fit in fits
    }
    exponent_values = np.asarray([fit.critical_exponent for fit in fits])
    core_checks = {
        "all_seven_theory_numerical_panels_generated": True,
        "three_display_depths_and_all_eight_fit_depths_present": (
            set(DISPLAY_DEPTHS).issubset(curves_by_depth) and tuple(fit.depth for fit in fits) == PAPER_DEPTHS
        ),
        "periodic_I3_curves_have_four_feature_sizes": all(
            len(curves_by_depth[depth]) == 4 for depth in PAPER_DEPTHS
        ),
        "I3_scans_are_predominantly_monotone_in_p": float(np.mean(monotonic_flags)) >= 0.8,
        "volume_law_I3_magnitude_grows_with_size": float(np.mean(volume_order_flags)) >= 0.8,
        "collapse_optimization_improves_over_no_size_scaling": all(
            fit.cost < fit.unscaled_cost for fit in fits
        ),
        "independent_pc_agrees_with_table_acceptance": float(np.mean(tuple(pc_errors.values()))) < 0.02,
        "critical_probabilities_are_inside_fit_windows": all(not fit.probability_at_boundary for fit in fits),
        "source_pixels_absent": True,
    }
    exponent_checks = {
        "all_exponents_are_inside_fit_bounds": all(not fit.exponent_at_boundary for fit in fits),
        "mean_exponent_is_near_paper_universal_value": abs(float(np.mean(exponent_values)) - 1.25) < 0.15,
        "depth_dependence_is_weak": float(np.ptp(exponent_values)) < 0.55,
    }
    core_pass = all(core_checks.values())
    exponent_pass = all(exponent_checks.values())
    return {
        "schema_version": 1,
        "paper_id": "1903.05124",
        "target_id": TARGET_ID,
        "status": "passed" if core_pass and exponent_pass else "passed_with_warnings" if core_pass else "failed",
        "scientific_feature_status": "passed" if core_pass and exponent_pass else "partial" if core_pass else "failed",
        "completion_status": "feature_reproduced" if core_pass and exponent_pass else "partial_reproduction",
        "generated_data_provenance": generated_data_provenance,
        "source_pixels_used_in_generation": False,
        "published_values_used_for_generation": False,
        "published_values_role": "post_fit_acceptance_only",
        "parameter_match": "paper_subset",
        "core_checks": core_checks,
        "critical_exponent_checks": exponent_checks,
        "metrics": {
            "display_depths": list(DISPLAY_DEPTHS),
            "fit_depths": list(PAPER_DEPTHS),
            "sizes": [curve.size for curve in curves_by_depth[DISPLAY_DEPTHS[0]]],
            "probability_points_per_depth": len(curves_by_depth[DISPLAY_DEPTHS[0]][0].measurement_fraction),
            "realizations_per_cell": 8,
            "scan_monotonic_fraction": float(np.mean(monotonic_flags)),
            "volume_order_fraction": float(np.mean(volume_order_flags)),
            "mean_pc_absolute_error": float(np.mean(tuple(pc_errors.values()))),
            "mean_nu_absolute_error": float(np.mean(tuple(nu_errors.values()))),
            "mean_fitted_nu": float(np.mean(exponent_values)),
            "fitted_nu_span": float(np.ptp(exponent_values)),
            "fits": {str(fit.depth): asdict(fit) for fit in fits},
            "published_acceptance": {
                str(depth): {"critical_probability": values[0], "critical_exponent": values[1]}
                for depth, values in PUBLISHED_ACCEPTANCE.items()
            },
        },
    }


def main() -> int:
    require_guard()
    args = parse_args()
    started = perf_counter()
    data_dir = WORKSPACE / "outputs" / "data"
    figure_dir = WORKSPACE / "outputs" / "figures"
    check_dir = WORKSPACE / "outputs" / "checks"
    for directory in (data_dir, figure_dir, check_dir):
        directory.mkdir(parents=True, exist_ok=True)

    inputs = (args.input, *args.refinement_input)
    curves = load_transition_curves(inputs)
    fits = fit_all_depths(curves, bootstrap_samples=args.bootstrap_samples, seed=args.seed)
    write_data_csv(data_dir / "supp_fig_s5_numerical_data.csv", curves, fits)
    write_fit_csv(data_dir / "supp_fig_s5_transition_fits.csv", fits)
    render(figure_dir / "supp_fig_s5_reproduction.png", curves, fits)
    provenance = (
        "independent_numerics_from_T001_plus_T005_midpoint_refinement"
        if args.refinement_input
        else "independent_numerics_reused_from_T001"
    )
    checks = build_checks(curves, fits, generated_data_provenance=provenance)
    checks["runtime_seconds"] = perf_counter() - started
    (check_dir / "t005_scientific_checks.json").write_text(
        json.dumps(checks, indent=2) + "\n", encoding="utf-8"
    )
    metadata = {
        "paper_id": "1903.05124",
        "target_id": TARGET_ID,
        "generated_data_provenance": provenance,
        "source_pixels_used_in_generation": False,
        "published_values_used_for_generation": False,
        "inputs": [
            f"{path.name}#campaign=transition,observable=tripartite_mutual_information"
            for path in inputs
        ],
        "formula_refs": ["EQC005", "EQC008"],
        "method_refs": ["MTH001", "MTH003"],
        "bootstrap_samples": args.bootstrap_samples,
        "seed": args.seed,
        "runtime_seconds": checks["runtime_seconds"],
    }
    (data_dir / "supp_fig_s5_metadata.json").write_text(
        json.dumps(metadata, indent=2) + "\n", encoding="utf-8"
    )
    print(json.dumps(checks, indent=2), flush=True)
    return 0 if checks["status"] != "failed" else 1


if __name__ == "__main__":
    raise SystemExit(main())
