#!/usr/bin/env python3
"""Render independent LDSI data in the paper's original figure geometry.

This module never reads source-figure pixels.  The source PDFs are used only to
record canvas and axes geometry in ``PAPER_GEOMETRY``.  Every scientific curve
comes from the case-local CSV files generated by the numerical solvers.
"""

from __future__ import annotations

import csv
import json
import os
from collections import defaultdict
from pathlib import Path

import matplotlib as mpl


CODE_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT_ROOT = CODE_ROOT.parent if CODE_ROOT.name == "code" else CODE_ROOT
OUTPUT_ROOT = Path(os.environ.get("LDSI_OUTPUT_ROOT", str(DEFAULT_OUTPUT_ROOT))).resolve()
os.environ.setdefault("MPLCONFIGDIR", str(OUTPUT_ROOT / ".cache" / "matplotlib"))
mpl.use("Agg")

import matplotlib.pyplot as plt  # noqa: E402
import numpy as np  # noqa: E402


DATA_DIR = OUTPUT_ROOT / "outputs" / "data"
FIGURE_DIR = OUTPUT_ROOT / "outputs" / "figures"
CHECK_DIR = OUTPUT_ROOT / "outputs" / "checks"
DPI = 180

# Canvas sizes and axes rectangles are measured from the vector source figures.
# Rectangles use Matplotlib's [left, bottom, width, height] figure coordinates.
PAPER_GEOMETRY = {
    "fig2": {
        "pixels": (1805, 1008),
        "main": (94.28 / 722.0, (403.0 - 334.60) / 403.0, (656.95 - 94.28) / 722.0, (334.60 - 30.40) / 403.0),
        "inset": (233.60 / 722.0, (403.0 - 215.80) / 403.0, (536.85 - 233.60) / 722.0, (215.80 - 59.80) / 403.0),
    },
    "fig3": {
        "pixels": (1378, 1383),
        "a": (58.26 / 551.0, (553.0 - 217.60) / 553.0, (491.93 - 58.26) / 551.0, (217.60 - 14.20) / 553.0),
        "b": (58.86 / 551.0, (553.0 - 372.40) / 553.0, (241.46 - 58.86) / 551.0, (372.40 - 267.40) / 553.0),
        "c": (304.53 / 551.0, (553.0 - 372.40) / 553.0, (490.73 - 304.53) / 551.0, (372.40 - 267.40) / 553.0),
        "d": (58.86 / 551.0, (553.0 - 517.60) / 553.0, (242.66 - 58.86) / 551.0, (517.60 - 418.00) / 553.0),
        "e": (305.73 / 551.0, (553.0 - 517.00) / 553.0, (490.13 - 305.73) / 551.0, (517.00 - 416.80) / 553.0),
        "e_inset": (347.78 / 551.0, (553.0 - 493.00) / 553.0, (464.90 - 347.78) / 551.0, (493.00 - 445.00) / 553.0),
    },
    # Published Fig. 4 crop (main article PDF), including its original right margin.
    "fig4": {
        "pixels": (935, 371),
        "a": (5 / 935, (371 - 271) / 371, (344 - 5) / 935, (271 - 20) / 371),
        "b": (438 / 935, (371 - 271) / 371, (778 - 438) / 935, (271 - 21) / 371),
    },
    # Supplementary Fig. S1 panel area; the caption is intentionally excluded.
    "figs1": {
        "pixels": (1722, 730),
        "a": (176 / 1722, (730 - 289) / 730, (583 - 176) / 1722, (289 - 36) / 730),
        "b": (699 / 1722, (730 - 290) / 730, (1107 - 699) / 1722, (290 - 36) / 730),
        "c": (1220 / 1722, (730 - 290) / 730, (1628 - 1220) / 1722, (290 - 36) / 730),
        "d": (404 / 1722, (730 - 658) / 730, (811 - 404) / 1722, (658 - 406) / 730),
        "e": (986 / 1722, (730 - 658) / 730, (1394 - 986) / 1722, (658 - 406) / 730),
    },
}


def _configure_style() -> None:
    mpl.rcParams.update(
        {
            "font.family": "sans-serif",
            "font.sans-serif": ["Helvetica", "Arial", "DejaVu Sans"],
            "mathtext.fontset": "cm",
            "axes.linewidth": 0.8,
            "axes.edgecolor": "#262626",
            "axes.labelcolor": "#262626",
            "xtick.color": "#262626",
            "ytick.color": "#262626",
            "xtick.direction": "in",
            "ytick.direction": "in",
            "xtick.top": True,
            "ytick.right": True,
            "legend.frameon": True,
            "legend.fancybox": False,
            "legend.edgecolor": "#262626",
            "legend.facecolor": "white",
            "legend.framealpha": 1.0,
            "pdf.fonttype": 42,
            "svg.fonttype": "none",
        }
    )


def _figure(kind: str) -> plt.Figure:
    width, height = PAPER_GEOMETRY[kind]["pixels"]
    # The epsilon prevents Agg from truncating an integer pixel because of a
    # binary floating-point representation just below the requested size.
    return plt.figure(figsize=((width + 1e-6) / DPI, (height + 1e-6) / DPI), dpi=DPI, facecolor="white")


def _save(fig: plt.Figure, stem: str) -> dict[str, object]:
    FIGURE_DIR.mkdir(parents=True, exist_ok=True)
    png = FIGURE_DIR / f"{stem}.png"
    pdf = FIGURE_DIR / f"{stem}.pdf"
    fig.savefig(png, dpi=DPI, facecolor="white")
    fig.savefig(pdf, dpi=DPI, facecolor="white")
    plt.close(fig)
    from PIL import Image

    size = Image.open(png).size
    return {"png": str(png.relative_to(OUTPUT_ROOT)), "pdf": str(pdf.relative_to(OUTPUT_ROOT)), "size": list(size)}


def _read_rows(name: str) -> list[dict[str, str]]:
    with (DATA_DIR / name).open(newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def _series(rows: list[dict[str, str]], x: str, y: str, **filters: object) -> tuple[np.ndarray, np.ndarray]:
    selected = [
        row
        for row in rows
        if all(np.isclose(float(row[key]), float(value)) if _is_number(value) else row[key] == str(value) for key, value in filters.items())
    ]
    return np.asarray([float(row[x]) for row in selected]), np.asarray([float(row[y]) for row in selected])


def _is_number(value: object) -> bool:
    return isinstance(value, (float, int, np.floating, np.integer))


def _paper_axes(ax: plt.Axes, tick_size: float, label_size: float, *, tick_length: float = 4.0) -> None:
    for spine in ax.spines.values():
        spine.set_visible(True)
        spine.set_linewidth(0.8)
        spine.set_color("#262626")
    ax.tick_params(labelsize=tick_size, width=0.8, length=tick_length, pad=4)
    ax.xaxis.label.set_size(label_size)
    ax.yaxis.label.set_size(label_size)


def render_fig2() -> dict[str, object]:
    rows = _read_rows("fig2_state_thresholds.csv")
    fig = _figure("fig2")
    ax = fig.add_axes(PAPER_GEOMETRY["fig2"]["main"])
    gaa_x, gaa_y = _series(rows, "energy_over_J", "eta_c_over_J", model="GAA")
    aa_x, aa_y = _series(rows, "energy_over_J", "eta_c_over_J", model="AA")
    ax.plot(gaa_x, gaa_y, color="#0000FF", lw=2.5, ls=":", label="GAA")
    ax.plot(aa_x, aa_y, color="#FF0000", lw=2.5, ls="-.", label="AA")
    ax.set(xlim=(-2.7, 2.7), ylim=(-0.01, 0.32), xticks=[-2, -1, 0, 1, 2], yticks=[0, 0.1, 0.2, 0.3])
    ax.set_xlabel(r"$\epsilon_{\alpha}/J$", fontsize=21, labelpad=4)
    ax.set_ylabel(r"$\eta_c$", fontsize=21, labelpad=8)
    _paper_axes(ax, 20, 21, tick_length=6)
    legend = ax.legend(loc="lower left", bbox_to_anchor=(0.035, 0.075), fontsize=20, handlelength=1.6, handletextpad=0.25, borderpad=0.2, labelspacing=0.25)
    legend.get_frame().set_linewidth(0.8)

    inset = fig.add_axes(PAPER_GEOMETRY["fig2"]["inset"])
    alpha, ipr = _series(rows, "alpha", "ipr", model="GAA")
    inset.plot(alpha, ipr, color="black", lw=1.8)
    inset.axvline(233, color="#808080", lw=1.6, ls="--", dashes=(4, 4))
    inset.text(166, 0.55, r"$\epsilon_c/J\simeq0.44$", color="#0000FF", fontsize=18)
    inset.set(xlim=(0, 377), ylim=(-0.03, 0.75), xticks=[0, 100, 200, 300], yticks=[0, 0.2, 0.4, 0.6])
    inset.set_xlabel(r"$\alpha$", fontsize=20, labelpad=0)
    inset.set_ylabel(r"$\mathrm{IPR}(\alpha)$", fontsize=20, labelpad=5)
    _paper_axes(inset, 17, 20, tick_length=4)
    return _save(fig, "fig2_pixel_registered")


def render_fig3() -> dict[str, object]:
    threshold = _read_rows("fig3_threshold.csv")
    momentum = _read_rows("fig3_momentum.csv")
    channels = _read_rows("fig3_channels.csv")
    fig = _figure("fig3")

    ax_a = fig.add_axes(PAPER_GEOMETRY["fig3"]["a"])
    chi, eta = _series(threshold, "chi_over_J", "eta_c_over_J")
    _, f1 = _series(threshold, "chi_over_J", "f1")
    ax_a.plot(chi, eta, color="#0000FF", lw=1.6, label=r"$\eta_c$")
    ax_a.set(xlim=(0, 3), ylim=(0, 0.3), xticks=[0.5, 1, 1.5, 2, 2.5, 3], yticks=[0, 0.1, 0.2, 0.3])
    ax_a.set_xlabel(r"$\chi$", fontsize=16, labelpad=2)
    ax_a.set_ylabel(r"$\eta_c$", fontsize=16, labelpad=4)
    _paper_axes(ax_a, 13, 16, tick_length=5)
    ax_a.text(0.035, 0.83, r"(a)   $\eta_c$", transform=ax_a.transAxes, fontsize=15)
    ax_a.axvline(2.0, color="black", lw=1.5, ls="--", dashes=(5, 4))

    ax_ar = ax_a.twinx()
    ax_ar.plot(chi, f1, color="#FF0000", lw=1.5, ls="-.", label=r"$f_1$")
    ax_ar.set_yscale("log")
    ax_ar.set(ylim=(1e-2, 1e4), yticks=[1e-2, 1e0, 1e2, 1e4])
    ax_ar.set_ylabel(r"$f_1$", fontsize=16, labelpad=4)
    _paper_axes(ax_ar, 13, 16, tick_length=5)
    ax_ar.text(0.69, 0.77, r"$f_1$", transform=ax_ar.transAxes, fontsize=18)
    lines = [ax_a.lines[0], ax_ar.lines[0]]
    legend = ax_a.legend(lines, [r"$\eta_c$", r"$f_1$"], loc="upper right", bbox_to_anchor=(0.976, 0.93), fontsize=13, handlelength=2.5, borderpad=0.35, labelspacing=0.25)
    legend.get_frame().set_linewidth(0.8)

    panel_specs = {
        "b": (0.0, 0.6),
        "c": (1.0, 0.02),
    }
    for panel, (chi_value, ymax) in panel_specs.items():
        ax = fig.add_axes(PAPER_GEOMETRY["fig3"][panel])
        q, ground = _series(momentum, "k_over_k1", "probability", chi_over_J=chi_value, state="ground")
        _, excited = _series(momentum, "k_over_k1", "probability", chi_over_J=chi_value, state="excited")
        ax.plot(q, ground, color="black", lw=1.0)
        ax.plot(q, excited, color="#0000FF", lw=1.0, ls="--", dashes=(6, 4))
        yticks = [0, 0.3, 0.6] if panel == "b" else [0, 0.01, 0.02]
        ax.set(xlim=(-2.1, 2.1), ylim=(0, ymax), xticks=[-2, 0, 2], yticks=yticks)
        ax.set_xlabel(r"$k/k_1$", fontsize=15, labelpad=1)
        if panel == "b":
            ax.set_ylabel(r"$p(k/k_1)$", fontsize=15, labelpad=1)
        _paper_axes(ax, 12, 15, tick_length=4)
        ax.text(0.08, 0.82, rf"$\chi={chi_value:g}$", transform=ax.transAxes, fontsize=14)
        ax.text(0.81, 0.84, rf"({panel})", transform=ax.transAxes, fontsize=14)
        if panel == "b":
            ax.annotate("", xy=(1.7, 0.20), xytext=(0.0, 0.20), arrowprops={"arrowstyle": "<->", "color": "#FF6929", "lw": 1.4})
            ax.text(0.72, 0.34, r"$k_c$", transform=ax.transAxes, fontsize=13)
        else:
            ax.annotate("", xy=(0.4, 0.0084), xytext=(-1.3, 0.0084), arrowprops={"arrowstyle": "<->", "color": "#FF6929", "lw": 1.3})
            ax.annotate("", xy=(0.9, 0.0032), xytext=(-0.8, 0.0032), arrowprops={"arrowstyle": "<->", "color": "#FF6929", "lw": 1.3})
            ax.text(0.32, 0.37, r"$k_c$", transform=ax.transAxes, fontsize=12)
            ax.text(0.52, 0.16, r"$k_c$", transform=ax.transAxes, fontsize=12)

    ax_d = fig.add_axes(PAPER_GEOMETRY["fig3"]["d"])
    alpha, f_chi1 = _series(channels, "alpha", "f1_alpha", chi_over_J=1.0)
    ax_d.plot(alpha, f_chi1, color="black", lw=0.9)
    ax_d.set(xlim=(0, 400), ylim=(0, 0.25), xticks=[0, 200, 400], yticks=[0, 0.1, 0.2])
    ax_d.set_xlabel(r"$\alpha$", fontsize=15, labelpad=1)
    ax_d.set_ylabel(r"$f_1^\alpha$", fontsize=15, labelpad=1)
    _paper_axes(ax_d, 12, 15, tick_length=4)
    ax_d.text(0.08, 0.80, r"$\chi=1$", transform=ax_d.transAxes, fontsize=14)
    ax_d.text(0.81, 0.82, "(d)", transform=ax_d.transAxes, fontsize=14)
    for index, label, dy in ((27, r"$\alpha_2$", 0.012), (137, r"$\alpha_1$", 0.012), (151, r"$\alpha_0$", 0.008)):
        value = float(f_chi1[np.argmin(np.abs(alpha - index))])
        ax_d.text(index, value + dy, label, ha="center", fontsize=12)

    ax_e = fig.add_axes(PAPER_GEOMETRY["fig3"]["e"])
    alpha_e, f_chi2 = _series(channels, "alpha", "f1_alpha", chi_over_J=2.03)
    mask = alpha_e >= 1
    ax_e.plot(alpha_e[mask], f_chi2[mask], color="black", lw=0.75)
    ax_e.set(xlim=(1, 400), ylim=(0, 4), xticks=[1, 200, 400], yticks=[0, 2, 4])
    ax_e.set_xlabel(r"$\alpha$", fontsize=15, labelpad=1)
    ax_e.set_ylabel(r"$f_1^\alpha$", fontsize=15, labelpad=1)
    _paper_axes(ax_e, 12, 15, tick_length=4)
    ax_e.text(0.16, 0.80, r"$\chi=2.03$", transform=ax_e.transAxes, fontsize=14)
    ax_e.text(0.81, 0.82, "(e)", transform=ax_e.transAxes, fontsize=14)

    inset = fig.add_axes(PAPER_GEOMETRY["fig3"]["e_inset"])
    q, localized = _series(momentum, "k_over_k1", "probability", chi_over_J=2.03, state="ground")
    inset.plot(q, localized, color="black", lw=0.75)
    inset.set(xlim=(-2, 2), ylim=(0, 0.01), xticks=[-2, 0, 2], yticks=[0, 0.01])
    _paper_axes(inset, 8, 9, tick_length=3)
    inset.text(0.09, 0.66, r"$p(k/k_1)$", transform=inset.transAxes, fontsize=9)
    return _save(fig, "fig3_pixel_registered")


def render_fig4() -> dict[str, object]:
    photon = _read_rows("fig4a_photon_number.csv")
    landscape = _read_rows("fig4b_threshold_landscape.csv")
    fig = _figure("fig4")

    ax_a = fig.add_axes(PAPER_GEOMETRY["fig4"]["a"])
    for chi_value, color, linestyle, dashes in (
        (0.5, "#0000FF", "-.", (3, 2, 1, 2)),
        (1.0, "#FF0000", "--", (5, 4)),
        (2.03, "#008000", "-", None),
    ):
        eta, photons = _series(photon, "eta_over_J", "photon_number", chi_over_J=chi_value)
        line, = ax_a.plot(eta, photons, color=color, lw=1.0, ls=linestyle, label=rf"$\chi/J={chi_value:g}$")
        if dashes:
            line.set_dashes(dashes)
    # The published panel suppresses y tick labels; its clipping points fix the
    # visible photon-number window to 0..5.
    ax_a.set(xlim=(0, 0.25), ylim=(0, 5.0), xticks=[0, 0.1, 0.2], yticks=[0, 1, 2, 3, 4, 5])
    ax_a.set_xticklabels(["0", "0.1", "0.2"])
    ax_a.set_yticklabels([])
    ax_a.set_xlabel(r"$\eta/J$", fontsize=13, labelpad=2)
    _paper_axes(ax_a, 11, 13, tick_length=3)
    ax_a.text(0.02, 0.90, "(a)", transform=ax_a.transAxes, fontsize=12)
    legend = ax_a.legend(loc="upper left", bbox_to_anchor=(0.13, 1.01), fontsize=10, handlelength=2.2, handletextpad=0.25, borderpad=0.2, labelspacing=0.05)
    legend.get_frame().set_linewidth(0.6)

    ax_b = fig.add_axes(PAPER_GEOMETRY["fig4"]["b"])
    colors = {0.0: "#FFFF00", 0.5: "#00E5E5", 1.5: "#00BDBD", 1.9: "#FF0000", 2.03: "#0000FF"}
    for chi_value in (0.0, 0.5, 1.5, 1.9, 2.03):
        gamma_c, eta_c = _series(landscape, "gamma_c", "eta_c_over_J", chi_over_J=chi_value)
        ax_b.fill_between(gamma_c, 0, eta_c, color=colors[chi_value], lw=0, label=rf"$\chi/J={chi_value:g}$")
    gamma = (np.sqrt(5.0) - 1.0) / 2.0
    for label, position in ((r"$2\gamma-1$", 2 * gamma - 1), (r"$1-\gamma$", 1 - gamma), (r"$\gamma$", gamma), (r"$2(1-\gamma)$", 2 * (1 - gamma))):
        ax_b.annotate("", xy=(position, 0.165), xytext=(position - 0.055, 0.255), arrowprops={"arrowstyle": "->", "color": "black", "lw": 0.8})
        ax_b.text(position - 0.16, 0.26, label, fontsize=9)
    ax_b.set(xlim=(0, 1), ylim=(0, 0.6), xticks=[0, 0.5, 1], yticks=[0, 0.3, 0.6])
    ax_b.set_xticklabels(["0", "0.5", "1"])
    ax_b.set_yticklabels(["0", "0.3", "0.6"])
    ax_b.set_xlabel(r"$\gamma_c$", fontsize=13, labelpad=1)
    ax_b.set_ylabel(r"$\eta_c$", fontsize=13, labelpad=2)
    _paper_axes(ax_b, 11, 13, tick_length=3)
    ax_b.text(0.02, 0.90, "(b)", transform=ax_b.transAxes, fontsize=12)
    legend = ax_b.legend(loc="upper right", bbox_to_anchor=(0.99, 0.99), fontsize=8.5, handlelength=1.25, handletextpad=0.25, borderpad=0.15, labelspacing=0.0)
    legend.get_frame().set_linewidth(0.6)
    return _save(fig, "fig4_pixel_registered")


def render_figs1() -> dict[str, object]:
    rows = _read_rows("figs1_density_profiles.csv")
    fig = _figure("figs1")
    panels = (("a", 0.0), ("b", 0.5), ("c", 1.0), ("d", 1.9), ("e", 2.03))
    limits = {
        0.0: ((0, 377), (0, 0.015), [0, 0.005, 0.01, 0.015]),
        0.5: ((0, 377), (0, 0.02), [0, 0.01, 0.02]),
        1.0: ((0, 377), (0, 0.06), [0, 0.02, 0.04, 0.06]),
        1.9: ((0, 377), (0, 0.2), [0, 0.1, 0.2]),
        2.03: ((65, 90), (0, 1.0), [0, 0.5, 1.0]),
    }
    for panel, chi_value in panels:
        ax = fig.add_axes(PAPER_GEOMETRY["figs1"][panel])
        sites, normal = _series(rows, "site", "probability", chi_over_J=chi_value, phase="normal")
        _, superradiant = _series(rows, "site", "probability", chi_over_J=chi_value, phase="superradiant")
        ax.plot(sites, normal, color="#0000FF", lw=1.2, label=r"$\eta<\eta_c$" if chi_value < 2 else r"$\eta=0$")
        red, = ax.plot(sites, superradiant, color="#FF0000", lw=1.0, ls=":", label=r"$\eta>\eta_c$" if chi_value < 2 else r"$\eta>0$")
        if chi_value == 2.03:
            red.set_marker("^")
            red.set_markevery(2)
            red.set_markersize(4)
        xlim, ylim, yticks = limits[chi_value]
        ax.set(xlim=xlim, ylim=ylim, yticks=yticks)
        ax.set_xlabel(r"$j$", fontsize=13, labelpad=1)
        ax.set_ylabel(r"$|\phi_0^j|^2$", fontsize=13, labelpad=2)
        _paper_axes(ax, 11, 13, tick_length=3)
        ax.text(0.03, 0.86, rf"({panel})  $\chi/J={chi_value:g}$", transform=ax.transAxes, fontsize=12)
        legend = ax.legend(loc="upper right", fontsize=10.5, handlelength=2.0, handletextpad=0.25, borderpad=0.2, labelspacing=0.1)
        legend.get_frame().set_linewidth(0.6)
        if chi_value in (0.0, 0.5, 1.0):
            ax.ticklabel_format(axis="y", style="sci", scilimits=(-2, -2), useMathText=True)
            ax.yaxis.get_offset_text().set_size(11)
    return _save(fig, "figs1_pixel_registered")


def main() -> int:
    _configure_style()
    artifacts = {
        "fig2": render_fig2(),
        "fig3": render_fig3(),
        "fig4": render_fig4(),
        "figs1": render_figs1(),
    }
    expected = {key: list(value["pixels"]) for key, value in PAPER_GEOMETRY.items()}
    checks = {key: artifacts[key]["size"] == expected[key] for key in artifacts}
    payload = {
        "status": "passed" if all(checks.values()) else "failed",
        "renderer": "independent_csv_to_paper_registered_matplotlib",
        "source_pixels_used": False,
        "dpi": DPI,
        "artifacts": artifacts,
        "geometry_checks": checks,
    }
    CHECK_DIR.mkdir(parents=True, exist_ok=True)
    (CHECK_DIR / "pixel_registered_render.json").write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    print(json.dumps(payload, indent=2))
    return 0 if payload["status"] == "passed" else 1


if __name__ == "__main__":
    raise SystemExit(main())
